### ISSUE TITLE
Unpredictable results.

### ISSUE THREAD

**Issue by doong-jo** [mskelton/vscode-react-emotion-snippets#3]
I typed `iec` but, result is `import { css, jsx } from '@emotion/core` 
I expected `import { css } from '@emotion/core` 

Is right?

**Comment by mskelton** [comment]
Thanks for reporting this issue.  While the snippet is correct, the readme is outdated which I just pushed a fix for.  The jsx import is required in Emotion 10 because Emotion uses the custom jsx pragma `/** @jsx jsx */`.

**Comment by mskelton** [comment]
@all-contributors add doong-jo to docs

**Comment by mskelton** [comment]
@all-contributors add @doong-jo to docs

**Comment by doong-jo** [comment]
Thank you for your response. Thanks to this, I am using the snippet well. :)
